name: Manual Deploy Laravel (Build & Upload)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, bcmath, curl, mysql, zip, fileinfo, tokenizer, ctype, json

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      - name: Build Laravel cache
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Prepare deployment folder
        run: |
          mkdir deploy
          rsync -av --progress . ./deploy \
            --exclude=.git \
            --exclude=node_modules \
            --exclude=tests \
            --exclude=.github \
            --exclude=storage \
            --exclude=.env

      - name: Upload build via sshpass + rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./deploy/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/laravel

      - name: Run post-deploy commands on server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/laravel
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
